[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.EarlyStopping>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.LearningRateMonitor>
Sanity Checking DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:166: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /n/netscratch/mahadevan_lab/Everyone/pafischer/walk- ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:612: UserWarning: Checkpoint directory checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [MIG-c42f28c5-8cdc-5353-a48e-8f8d287c348d]
  | Name  | Type        | Params
--------------------------------------
0 | model | ByteNetArch | 1.0 M
--------------------------------------
1.0 M     Trainable params
0         Non-trainable params
1.0 M     Total params
4.104     Total estimated model params size (MB)
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:1600: PossibleUserWarning: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(

Epoch 0: 100%|██████████| 2/2 [00:01<00:00,  1.41it/s, loss=0.351, v_num=gxno]
Epoch 1, global step 2: 'val_loss' reached 0.22279 (best 0.22279), saving model to 'checkpoints/epoch=1-step=2-val_loss=0.2228.ckpt' as top 2
Epoch 2, global step 3: 'val_loss' reached 0.17752 (best 0.17752), saving model to 'checkpoints/epoch=2-step=3-val_loss=0.1775-v3.ckpt' as top 3
Epoch 3, global step 4: 'val_loss' reached 0.15600 (best 0.15600), saving model to 'checkpoints/epoch=3-step=4-val_loss=0.1560-v1.ckpt' as top 4
Epoch 4, global step 5: 'val_loss' reached 0.14239 (best 0.14239), saving model to 'checkpoints/epoch=4-step=5-val_loss=0.1424-v1.ckpt' as top 5

Epoch 5: 100%|██████████| 2/2 [00:00<00:00, 10.64it/s, loss=0.23, v_num=gxno]
Epoch 6, global step 7: 'val_loss' reached 0.11733 (best 0.11733), saving model to 'checkpoints/epoch=6-step=7-val_loss=0.1173-v1.ckpt' as top 7
Epoch 7, global step 8: 'val_loss' reached 0.10364 (best 0.10364), saving model to 'checkpoints/epoch=7-step=8-val_loss=0.1036-v1.ckpt' as top 8
Epoch 8, global step 9: 'val_loss' reached 0.09259 (best 0.09259), saving model to 'checkpoints/epoch=8-step=9-val_loss=0.0926.ckpt' as top 9

Epoch 11: 100%|██████████| 2/2 [00:00<00:00, 10.44it/s, loss=0.166, v_num=gxno]
Epoch 10, global step 11: 'val_loss' reached 0.07763 (best 0.07763), saving model to 'checkpoints/epoch=10-step=11-val_loss=0.0776-v2.ckpt' as top 11
Epoch 11, global step 12: 'val_loss' reached 0.07322 (best 0.07322), saving model to 'checkpoints/epoch=11-step=12-val_loss=0.0732-v3.ckpt' as top 12
Epoch 12, global step 13: 'val_loss' reached 0.06832 (best 0.06832), saving model to 'checkpoints/epoch=12-step=13-val_loss=0.0683-v8.ckpt' as top 13
Epoch 13, global step 14: 'val_loss' reached 0.06618 (best 0.06618), saving model to 'checkpoints/epoch=13-step=14-val_loss=0.0662-v2.ckpt' as top 14

Epoch 15:   0%|          | 0/2 [00:00<?, ?it/s, loss=0.146, v_num=gxno]
Epoch 15, global step 16: 'val_loss' reached 0.06098 (best 0.06098), saving model to 'checkpoints/epoch=15-step=16-val_loss=0.0610-v4.ckpt' as top 16
Epoch 16, global step 17: 'val_loss' reached 0.06081 (best 0.06081), saving model to 'checkpoints/epoch=16-step=17-val_loss=0.0608-v4.ckpt' as top 17
Epoch 17, global step 18: 'val_loss' reached 0.05901 (best 0.05901), saving model to 'checkpoints/epoch=17-step=18-val_loss=0.0590-v6.ckpt' as top 18
Epoch 18, global step 19: 'val_loss' reached 0.05809 (best 0.05809), saving model to 'checkpoints/epoch=18-step=19-val_loss=0.0581-v6.ckpt' as top 19


Epoch 19: 100%|██████████| 2/2 [00:00<00:00,  4.71it/s, loss=0.125, v_num=gxno]
`Trainer.fit` stopped: `max_epochs=20` reached.