[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.EarlyStopping>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.LearningRateMonitor>
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:166: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python my_experiment.py ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Error executing job with overrides: []
Traceback (most recent call last):
  File "/n/netscratch/mahadevan_lab/Everyone/pafischer/walk-jump-fork/src/walkjump/cmdline/_train.py", line 41, in train
    trainer.fit(model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1033, in _run
    self._data_connector.prepare_data()
  File "/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 107, in prepare_data
    dm_prepare_data_per_node = datamodule.prepare_data_per_node
AttributeError: 'AbDataModule' object has no attribute 'prepare_data_per_node'
