[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.EarlyStopping>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.LearningRateMonitor>
Epoch 1: 100%|██████████| 2/2 [00:00<00:00,  9.93it/s, loss=0.341, v_num=ltic]
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:166: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python my_experiment.py ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:612: UserWarning: Checkpoint directory checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [MIG-c520cbb9-133b-5a16-81a3-2b18e3f38047]
  | Name  | Type        | Params
--------------------------------------
0 | model | ByteNetArch | 1.0 M
--------------------------------------
1.0 M     Trainable params
0         Non-trainable params
1.0 M     Total params
4.104     Total estimated model params size (MB)
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:1600: PossibleUserWarning: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 0, global step 1: 'val_loss' reached 0.33249 (best 0.33249), saving model to 'checkpoints/epoch=0-step=1-val_loss=0.3325-v1.ckpt' as top 1
Epoch 1, global step 2: 'val_loss' reached 0.22129 (best 0.22129), saving model to 'checkpoints/epoch=1-step=2-val_loss=0.2213.ckpt' as top 2
Epoch 2, global step 3: 'val_loss' reached 0.17730 (best 0.17730), saving model to 'checkpoints/epoch=2-step=3-val_loss=0.1773.ckpt' as top 3
Epoch 3, global step 4: 'val_loss' reached 0.15659 (best 0.15659), saving model to 'checkpoints/epoch=3-step=4-val_loss=0.1566.ckpt' as top 4
Epoch 4, global step 5: 'val_loss' reached 0.14293 (best 0.14293), saving model to 'checkpoints/epoch=4-step=5-val_loss=0.1429.ckpt' as top 5

Epoch 6:   0%|          | 0/2 [00:00<?, ?it/s, loss=0.23, v_num=ltic]
Epoch 6, global step 7: 'val_loss' reached 0.11756 (best 0.11756), saving model to 'checkpoints/epoch=6-step=7-val_loss=0.1176.ckpt' as top 7
Epoch 7, global step 8: 'val_loss' reached 0.10320 (best 0.10320), saving model to 'checkpoints/epoch=7-step=8-val_loss=0.1032.ckpt' as top 8
Epoch 8, global step 9: 'val_loss' reached 0.09302 (best 0.09302), saving model to 'checkpoints/epoch=8-step=9-val_loss=0.0930.ckpt' as top 9

Epoch 10:  50%|█████     | 1/2 [00:00<00:00,  8.78it/s, loss=0.173, v_num=ltic]
Epoch 10, global step 11: 'val_loss' reached 0.07809 (best 0.07809), saving model to 'checkpoints/epoch=10-step=11-val_loss=0.0781.ckpt' as top 11
Epoch 11, global step 12: 'val_loss' reached 0.07339 (best 0.07339), saving model to 'checkpoints/epoch=11-step=12-val_loss=0.0734-v1.ckpt' as top 12
Epoch 12, global step 13: 'val_loss' reached 0.06837 (best 0.06837), saving model to 'checkpoints/epoch=12-step=13-val_loss=0.0684-v1.ckpt' as top 13
Epoch 13, global step 14: 'val_loss' reached 0.06626 (best 0.06626), saving model to 'checkpoints/epoch=13-step=14-val_loss=0.0663.ckpt' as top 14

Epoch 14: 100%|██████████| 2/2 [00:00<00:00,  9.73it/s, loss=0.146, v_num=ltic]
Epoch 15, global step 16: 'val_loss' reached 0.06096 (best 0.06096), saving model to 'checkpoints/epoch=15-step=16-val_loss=0.0610-v1.ckpt' as top 16
Epoch 16, global step 17: 'val_loss' reached 0.06071 (best 0.06071), saving model to 'checkpoints/epoch=16-step=17-val_loss=0.0607-v1.ckpt' as top 17
Epoch 17, global step 18: 'val_loss' reached 0.05916 (best 0.05916), saving model to 'checkpoints/epoch=17-step=18-val_loss=0.0592.ckpt' as top 18
Epoch 19:  50%|█████     | 1/2 [00:00<00:00,  8.64it/s, loss=0.125, v_num=ltic]

Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 19, global step 20: 'val_loss' reached 0.05742 (best 0.05742), saving model to 'checkpoints/epoch=19-step=20-val_loss=0.0574.ckpt' as top 20
`Trainer.fit` stopped: `max_epochs=20` reached.