[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.EarlyStopping>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.LearningRateMonitor>
Epoch 1: 100%|██████████| 2/2 [00:00<00:00, 10.42it/s, loss=0.341, v_num=vakz]
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:166: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /n/netscratch/mahadevan_lab/Everyone/pafischer/walk- ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:612: UserWarning: Checkpoint directory checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [MIG-c42f28c5-8cdc-5353-a48e-8f8d287c348d]
  | Name  | Type        | Params
--------------------------------------
0 | model | ByteNetArch | 1.0 M
--------------------------------------
1.0 M     Trainable params
0         Non-trainable params
1.0 M     Total params
4.104     Total estimated model params size (MB)
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:1600: PossibleUserWarning: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 0, global step 1: 'val_loss' reached 0.33428 (best 0.33428), saving model to 'checkpoints/epoch=0-step=1-val_loss=0.3343.ckpt' as top 1

Epoch 6: 100%|██████████| 2/2 [00:00<00:00, 10.46it/s, loss=0.216, v_num=vakz]
Epoch 2, global step 3: 'val_loss' reached 0.17716 (best 0.17716), saving model to 'checkpoints/epoch=2-step=3-val_loss=0.1772-v3.ckpt' as top 3
Epoch 3, global step 4: 'val_loss' reached 0.15659 (best 0.15659), saving model to 'checkpoints/epoch=3-step=4-val_loss=0.1566-v2.ckpt' as top 4
Epoch 4, global step 5: 'val_loss' reached 0.14201 (best 0.14201), saving model to 'checkpoints/epoch=4-step=5-val_loss=0.1420-v1.ckpt' as top 5
Epoch 5, global step 6: 'val_loss' reached 0.13202 (best 0.13202), saving model to 'checkpoints/epoch=5-step=6-val_loss=0.1320-v1.ckpt' as top 6
Epoch 6, global step 7: 'val_loss' reached 0.11731 (best 0.11731), saving model to 'checkpoints/epoch=6-step=7-val_loss=0.1173-v2.ckpt' as top 7
Epoch 7, global step 8: 'val_loss' reached 0.10328 (best 0.10328), saving model to 'checkpoints/epoch=7-step=8-val_loss=0.1033-v1.ckpt' as top 8
Epoch 8, global step 9: 'val_loss' reached 0.09323 (best 0.09323), saving model to 'checkpoints/epoch=8-step=9-val_loss=0.0932-v2.ckpt' as top 9
Epoch 9, global step 10: 'val_loss' reached 0.08460 (best 0.08460), saving model to 'checkpoints/epoch=9-step=10-val_loss=0.0846-v3.ckpt' as top 10

Epoch 10: 100%|██████████| 2/2 [00:00<00:00, 10.14it/s, loss=0.174, v_num=vakz]
Epoch 11, global step 12: 'val_loss' reached 0.07336 (best 0.07336), saving model to 'checkpoints/epoch=11-step=12-val_loss=0.0734-v3.ckpt' as top 12
Epoch 12, global step 13: 'val_loss' reached 0.06827 (best 0.06827), saving model to 'checkpoints/epoch=12-step=13-val_loss=0.0683-v9.ckpt' as top 13
Epoch 13, global step 14: 'val_loss' reached 0.06611 (best 0.06611), saving model to 'checkpoints/epoch=13-step=14-val_loss=0.0661-v3.ckpt' as top 14
Epoch 15:  50%|█████     | 1/2 [00:00<00:00,  9.16it/s, loss=0.141, v_num=vakz]
Validation: 0it [00:00, ?it/s]
Epoch 15, global step 16: 'val_loss' reached 0.06098 (best 0.06098), saving model to 'checkpoints/epoch=15-step=16-val_loss=0.0610-v5.ckpt' as top 16
Epoch 16, global step 17: 'val_loss' reached 0.06092 (best 0.06092), saving model to 'checkpoints/epoch=16-step=17-val_loss=0.0609-v2.ckpt' as top 17
Epoch 17, global step 18: 'val_loss' reached 0.05910 (best 0.05910), saving model to 'checkpoints/epoch=17-step=18-val_loss=0.0591-v3.ckpt' as top 18
Epoch 18, global step 19: 'val_loss' reached 0.05815 (best 0.05815), saving model to 'checkpoints/epoch=18-step=19-val_loss=0.0581-v7.ckpt' as top 19
Epoch 19, global step 20: 'val_loss' reached 0.05735 (best 0.05735), saving model to 'checkpoints/epoch=19-step=20-val_loss=0.0573-v7.ckpt' as top 20

`Trainer.fit` stopped: `max_epochs=20` reached.